language: node_js
node_js: 0.12
before_install:
  - "npm install -g coffee-script"
  - "npm install path@0.11"
  - "npm install util"
  - "npm install mocha"
  - "npm install -g phantomjs@1.9.20"
  - "npm install mocha-phantomjs"
  - "cake build"
script: "cake test"
notifications:
  email: false
branches:
  except:
    - experimental
    - 1.43
    - commands
